package com.ac.mule.stripe;

import java.util.HashMap;
import java.util.Map;

import org.joda.time.DateTime;

/**
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 **/

/**
 * This file was automatically generated by the Mule Development Kit
 */
public class CreditCardTokenGenerator {
    
  public static Map<String, Object> generateCreditCardToken() throws Exception {

    Map<String, Object> tokenParams = new HashMap<String, Object>();
    Map<String, Object> cardParams = new HashMap<String, Object>();
    cardParams.put("number", "4242424242424242");
    cardParams.put("exp_month", 4);
    cardParams.put("exp_year", DateTime.now().getYear() + 1);
    cardParams.put("cvc", "314");
    tokenParams.put("card", cardParams);

    return tokenParams;

  }

  public static Map<String, Object> generateCreditCardTokenFailCVC() throws Exception {

    Map<String, Object> tokenParams = new HashMap<String, Object>();
    Map<String, Object> cardParams = new HashMap<String, Object>();
    cardParams.put("number", "4000000000000127");
    cardParams.put("exp_month", 4);
    cardParams.put("exp_year", DateTime.now().getYear() + 1);
    cardParams.put("cvc", "314");
    tokenParams.put("card", cardParams);

    return tokenParams;

  }

  public static Map<String, Object> generateCreditCardTokenFailExpired() throws Exception {

    Map<String, Object> tokenParams = new HashMap<String, Object>();
    Map<String, Object> cardParams = new HashMap<String, Object>();
    cardParams.put("number", "4000000000000069");
    cardParams.put("exp_month", 4);
    cardParams.put("exp_year", DateTime.now().getYear() + 1);
    cardParams.put("cvc", "314");
    tokenParams.put("card", cardParams);

    return tokenParams;

  }

  public static Map<String, Object> generateCreditCardTokenFail() throws Exception {

    Map<String, Object> tokenParams = new HashMap<String, Object>();
    Map<String, Object> cardParams = new HashMap<String, Object>();
    cardParams.put("number", "4000000000000119");
    cardParams.put("exp_month", 4);
    cardParams.put("exp_year", DateTime.now().getYear() + 1);
    cardParams.put("cvc", "314");
    tokenParams.put("card", cardParams);

    return tokenParams;

  }
  
  public static Map<String, Object> generateCreditCardTokenDeclineCharge() throws Exception {

    Map<String, Object> tokenParams = new HashMap<String, Object>();
    Map<String, Object> cardParams = new HashMap<String, Object>();
    cardParams.put("number", "4000000000000341");
    cardParams.put("exp_month", 4);
    cardParams.put("exp_year", DateTime.now().getYear() + 1);
    cardParams.put("cvc", "314");
    tokenParams.put("card", cardParams);

    return tokenParams;

  }

}
